export const cities = [
    { "id": "1", "governorate_id": "1", "city_name_ar": "15 مايو", "city_name_en": "15 May", "big_city":"Cairo" },
    { "id": "2", "governorate_id": "1", "city_name_ar": "الازبكية", "city_name_en": "Al Azbakeyah", "big_city":"Cairo" },
    { "id": "3", "governorate_id": "1", "city_name_ar": "البساتين", "city_name_en": "Al Basatin" , "big_city":"Cairo"},
    { "id": "4", "governorate_id": "1", "city_name_ar": "التبين", "city_name_en": "Tebin" , "big_city":"Cairo"},
    { "id": "5", "governorate_id": "1", "city_name_ar": "الخليفة", "city_name_en": "El-Khalifa", "big_city":"Cairo" },
    { "id": "6", "governorate_id": "1", "city_name_ar": "الدراسة", "city_name_en": "El darrasa", "big_city":"Cairo" },
    { "id": "7", "governorate_id": "1", "city_name_ar": "الدرب الاحمر", "city_name_en": "Aldarb Alahmar", "big_city":"Cairo" },
    { "id": "8", "governorate_id": "1", "city_name_ar": "الزاوية الحمراء", "city_name_en": "Zawya al-Hamra" , "big_city":"Cairo"},
    { "id": "9", "governorate_id": "1", "city_name_ar": "الزيتون", "city_name_en": "El-Zaytoun" , "big_city":"Cairo"},
    { "id": "10", "governorate_id": "1", "city_name_ar": "الساحل", "city_name_en": "Sahel" , "big_city":"Cairo"},
    { "id": "11", "governorate_id": "1", "city_name_ar": "السلام", "city_name_en": "El Salam" , "big_city":"Cairo"},
    { "id": "12", "governorate_id": "1", "city_name_ar": "السيدة زينب", "city_name_en": "Sayeda Zeinab", "big_city":"Cairo" },
    { "id": "13", "governorate_id": "1", "city_name_ar": "الشرابية", "city_name_en": "El Sharabeya" , "big_city":"Cairo"},
    { "id": "14", "governorate_id": "1", "city_name_ar": "مدينة الشروق", "city_name_en": "Shorouk" , "big_city":"Cairo"},
    { "id": "15", "governorate_id": "1", "city_name_ar": "الظاهر", "city_name_en": "El Daher" , "big_city":"Cairo"},
    { "id": "16", "governorate_id": "1", "city_name_ar": "العتبة", "city_name_en": "Ataba", "big_city":"Cairo" },
    { "id": "17", "governorate_id": "1", "city_name_ar": "القاهرة الجديدة", "city_name_en": "New Cairo" , "big_city":"Cairo"},
    { "id": "18", "governorate_id": "1", "city_name_ar": "المرج", "city_name_en": "El Marg" , "big_city":"Cairo"},
    { "id": "19", "governorate_id": "1", "city_name_ar": "عزبة النخل", "city_name_en": "Ezbet el Nakhl", "big_city":"Cairo" },
    { "id": "20", "governorate_id": "1", "city_name_ar": "المطرية", "city_name_en": "Matareya", "big_city":"Cairo" },
    { "id": "21", "governorate_id": "1", "city_name_ar": "المعادى", "city_name_en": "Maadi", "big_city":"Cairo" },
    { "id": "22", "governorate_id": "1", "city_name_ar": "المعصرة", "city_name_en": "Maasara", "big_city":"Cairo" },
    { "id": "23", "governorate_id": "1", "city_name_ar": "المقطم", "city_name_en": "Mokattam" , "big_city":"Cairo"},
    { "id": "24", "governorate_id": "1", "city_name_ar": "المنيل", "city_name_en": "Manyal" , "big_city":"Cairo"},
    { "id": "25", "governorate_id": "1", "city_name_ar": "الموسكى", "city_name_en": "Mosky", "big_city":"Cairo" },
    { "id": "26", "governorate_id": "1", "city_name_ar": "النزهة", "city_name_en": "Nozha" , "big_city":"Cairo"},
    { "id": "27", "governorate_id": "1", "city_name_ar": "الوايلى", "city_name_en": "Waily", "big_city":"Cairo" },
    { "id": "28", "governorate_id": "1", "city_name_ar": "باب الشعرية", "city_name_en": "Bab al-Shereia" , "big_city":"Cairo"},
    { "id": "29", "governorate_id": "1", "city_name_ar": "بولاق", "city_name_en": "Bolaq" , "big_city":"Cairo"},
    { "id": "30", "governorate_id": "1", "city_name_ar": "جاردن سيتى", "city_name_en": "Garden City" , "big_city":"Cairo"},
    { "id": "31", "governorate_id": "1", "city_name_ar": "حدائق القبة", "city_name_en": "Hadayek El-Kobba", "big_city":"Cairo" },
    { "id": "32", "governorate_id": "1", "city_name_ar": "حلوان", "city_name_en": "Helwan", "big_city":"Cairo" },
    { "id": "33", "governorate_id": "1", "city_name_ar": "دار السلام", "city_name_en": "Dar Al Salam", "big_city":"Cairo" },
    { "id": "34", "governorate_id": "1", "city_name_ar": "شبرا", "city_name_en": "Shubra", "big_city":"Cairo" },
    { "id": "35", "governorate_id": "1", "city_name_ar": "طره", "city_name_en": "Tura" , "big_city":"Cairo"},
    { "id": "36", "governorate_id": "1", "city_name_ar": "عابدين", "city_name_en": "Abdeen", "big_city":"Cairo" },
    { "id": "37", "governorate_id": "1", "city_name_ar": "عباسية", "city_name_en": "Abaseya", "big_city":"Cairo" },
    { "id": "38", "governorate_id": "1", "city_name_ar": "عين شمس", "city_name_en": "Ain Shams", "big_city":"Cairo" },
    { "id": "39", "governorate_id": "1", "city_name_ar": "مدينة نصر", "city_name_en": "Nasr City", "big_city":"Cairo" },
    { "id": "40", "governorate_id": "1", "city_name_ar": "مصر الجديدة", "city_name_en": "New Heliopolis" , "big_city":"Cairo"},
    { "id": "41", "governorate_id": "1", "city_name_ar": "مصر القديمة", "city_name_en": "Masr Al Qadima" , "big_city":"Cairo"},
    { "id": "42", "governorate_id": "1", "city_name_ar": "منشية ناصر", "city_name_en": "Mansheya Nasir" , "big_city":"Cairo"},
    { "id": "43", "governorate_id": "1", "city_name_ar": "مدينة بدر", "city_name_en": "Badr City" , "big_city":"Cairo"},
    { "id": "44", "governorate_id": "1", "city_name_ar": "مدينة العبور", "city_name_en": "Obour City" , "big_city":"Cairo"},
    { "id": "45", "governorate_id": "1", "city_name_ar": "وسط البلد", "city_name_en": "Cairo Downtown", "big_city":"Cairo"},
    { "id": "46", "governorate_id": "1", "city_name_ar": "الزمالك", "city_name_en": "Zamalek" },
    { "id": "47", "governorate_id": "1", "city_name_ar": "قصر النيل", "city_name_en": "Kasr El Nile", "big_city":"Cairo" },
    { "id": "48", "governorate_id": "1", "city_name_ar": "الرحاب", "city_name_en": "Rehab", "big_city":"Cairo" },
    { "id": "49", "governorate_id": "1", "city_name_ar": "القطامية", "city_name_en": "Katameya" , "big_city":"Cairo"},
    { "id": "50", "governorate_id": "1", "city_name_ar": "مدينتي", "city_name_en": "Madinty" , "big_city":"Cairo"},
    { "id": "51", "governorate_id": "1", "city_name_ar": "روض الفرج", "city_name_en": "Rod Alfarag" , "big_city":"Cairo"},
    { "id": "52", "governorate_id": "1", "city_name_ar": "شيراتون", "city_name_en": "Sheraton", "big_city":"Cairo" },
    { "id": "53", "governorate_id": "1", "city_name_ar": "الجمالية", "city_name_en": "El-Gamaleya", "big_city":"Cairo" },
    { "id": "54", "governorate_id": "1", "city_name_ar": "العاشر من رمضان", "city_name_en": "10th of Ramadan City", "big_city":"Cairo" },
    { "id": "55", "governorate_id": "1", "city_name_ar": "الحلمية", "city_name_en": "Helmeyat Alzaytoun", "big_city":"Cairo" },
    { "id": "56", "governorate_id": "1", "city_name_ar": "النزهة الجديدة", "city_name_en": "New Nozha" , "big_city":"Cairo"},
    { "id": "57", "governorate_id": "1", "city_name_ar": "العاصمة الإدارية", "city_name_en": "Capital New", "big_city":"Cairo" },
    { "id": "58", "governorate_id": "2", "city_name_ar": "الجيزة", "city_name_en": "Giza" , "big_city":"Giza"},
    { "id": "59", "governorate_id": "2", "city_name_ar": "السادس من أكتوبر", "city_name_en": "Sixth of October","big_city":"Giza" },
    { "id": "60", "governorate_id": "2", "city_name_ar": "الشيخ زايد", "city_name_en": "Cheikh Zayed" ,"big_city":"Giza"},
    { "id": "61", "governorate_id": "2", "city_name_ar": "الحوامدية", "city_name_en": "Hawamdiyah","big_city":"Giza" },
    { "id": "62", "governorate_id": "2", "city_name_ar": "البدرشين", "city_name_en": "Al Badrasheen" ,"big_city":"Giza"},
    { "id": "63", "governorate_id": "2", "city_name_ar": "الصف", "city_name_en": "Saf","big_city":"Giza" },
    { "id": "64", "governorate_id": "2", "city_name_ar": "أطفيح", "city_name_en": "Atfih","big_city":"Giza" },
    { "id": "65", "governorate_id": "2", "city_name_ar": "العياط", "city_name_en": "Al Ayat","big_city":"Giza" },
    { "id": "66", "governorate_id": "2", "city_name_ar": "الباويطي", "city_name_en": "Al-Bawaiti" ,"big_city":"Giza"},
    { "id": "67", "governorate_id": "2", "city_name_ar": "منشأة القناطر", "city_name_en": "ManshiyetAl Qanater" ,"big_city":"Giza"},
    { "id": "68", "governorate_id": "2", "city_name_ar": "أوسيم", "city_name_en": "Oaseem" ,"big_city":"Giza"},
    { "id": "69", "governorate_id": "2", "city_name_ar": "كرداسة", "city_name_en": "Kerdasa","big_city":"Giza" },
    { "id": "70", "governorate_id": "2", "city_name_ar": "أبو النمرس", "city_name_en": "Abu Nomros" ,"big_city":"Giza"},
    { "id": "71", "governorate_id": "2", "city_name_ar": "كفر غطاطي", "city_name_en": "Kafr Ghati","big_city":"Giza" },
    { "id": "72", "governorate_id": "2", "city_name_ar": "منشأة البكاري", "city_name_en": "Manshiyet Al Bakari","big_city":"Giza" },
    { "id": "73", "governorate_id": "2", "city_name_ar": "الدقى", "city_name_en": "Dokki" ,"big_city":"Giza"},
    { "id": "74", "governorate_id": "2", "city_name_ar": "العجوزة", "city_name_en": "Agouza" ,"big_city":"Giza"},
    { "id": "75", "governorate_id": "2", "city_name_ar": "الهرم", "city_name_en": "Haram" ,"big_city":"Giza"},
    { "id": "76", "governorate_id": "2", "city_name_ar": "الوراق", "city_name_en": "Warraq" ,"big_city":"Giza"},
    { "id": "77", "governorate_id": "2", "city_name_ar": "امبابة", "city_name_en": "Imbaba" ,"big_city":"Giza"},
    { "id": "78", "governorate_id": "2", "city_name_ar": "بولاق الدكرور", "city_name_en": "Boulaq Dakrour" ,"big_city":"Giza"},
    { "id": "79", "governorate_id": "2", "city_name_ar": "الواحات البحرية", "city_name_en": "Al Wahat Al Baharia" ,"big_city":"Giza"},
    { "id": "80", "governorate_id": "2", "city_name_ar": "العمرانية", "city_name_en": "Omraneya" ,"big_city":"Giza"},
    { "id": "81", "governorate_id": "2", "city_name_ar": "المنيب", "city_name_en": "Moneeb","big_city":"Giza" },
    { "id": "82", "governorate_id": "2", "city_name_ar": "بين السرايات", "city_name_en": "Bin Alsarayat","big_city":"Giza" },
    { "id": "83", "governorate_id": "2", "city_name_ar": "الكيت كات", "city_name_en": "Kit Kat" ,"big_city":"Giza"},
    { "id": "84", "governorate_id": "2", "city_name_ar": "المهندسين", "city_name_en": "Mohandessin","big_city":"Giza" },
    { "id": "85", "governorate_id": "2", "city_name_ar": "فيصل", "city_name_en": "Faisal" ,"big_city":"Giza"},
    { "id": "86", "governorate_id": "2", "city_name_ar": "أبو رواش", "city_name_en": "Abu Rawash" ,"big_city":"Giza"},
    { "id": "87", "governorate_id": "2", "city_name_ar": "حدائق الأهرام", "city_name_en": "Hadayek Alahram" ,"big_city":"Giza"},
    { "id": "88", "governorate_id": "2", "city_name_ar": "الحرانية", "city_name_en": "Haraneya","big_city":"Giza" },
    { "id": "89", "governorate_id": "2", "city_name_ar": "حدائق اكتوبر", "city_name_en": "Hadayek October","big_city":"Giza" },
    { "id": "90", "governorate_id": "2", "city_name_ar": "صفط اللبن", "city_name_en": "Saft Allaban","big_city":"Giza" },
    { "id": "91", "governorate_id": "2", "city_name_ar": "القرية الذكية", "city_name_en": "Smart Village","big_city":"Giza" },
    { "id": "92", "governorate_id": "2", "city_name_ar": "ارض اللواء", "city_name_en": "Ard Ellwaa","big_city":"Giza" },

    { "id": "93", "governorate_id": "3", "city_name_ar": "ابو قير", "city_name_en": "Abu Qir" ,"big_city":"Alexandria"},
    { "id": "94", "governorate_id": "3", "city_name_ar": "الابراهيمية", "city_name_en": "Al Ibrahimeyah","big_city":"Alexandria" },
    { "id": "95", "governorate_id": "3", "city_name_ar": "الأزاريطة", "city_name_en": "Azarita" ,"big_city":"Alexandria"},
    { "id": "96", "governorate_id": "3", "city_name_ar": "الانفوشى", "city_name_en": "Anfoushi" ,"big_city":"Alexandria"},
    { "id": "97", "governorate_id": "3", "city_name_ar": "الدخيلة", "city_name_en": "Dekheila" ,"big_city":"Alexandria"},
    { "id": "98", "governorate_id": "3", "city_name_ar": "السيوف", "city_name_en": "El Soyof" ,"big_city":"Alexandria"},
    { "id": "99", "governorate_id": "3", "city_name_ar": "العامرية", "city_name_en": "Ameria" ,"big_city":"Alexandria"},
    { "id": "100", "governorate_id": "3", "city_name_ar": "اللبان", "city_name_en": "El Labban" ,"big_city":"Alexandria"},
    { "id": "101", "governorate_id": "3", "city_name_ar": "المفروزة", "city_name_en": "Al Mafrouza" ,"big_city":"Alexandria"},
    { "id": "102", "governorate_id": "3", "city_name_ar": "المنتزه", "city_name_en": "El Montaza" ,"big_city":"Alexandria"},
    { "id": "103", "governorate_id": "3", "city_name_ar": "المنشية", "city_name_en": "Mansheya" ,"big_city":"Alexandria"},
    { "id": "104", "governorate_id": "3", "city_name_ar": "الناصرية", "city_name_en": "Naseria","big_city":"Alexandria" },
    { "id": "105", "governorate_id": "3", "city_name_ar": "امبروزو", "city_name_en": "Ambrozo","big_city":"Alexandria" },
    { "id": "106", "governorate_id": "3", "city_name_ar": "باب شرق", "city_name_en": "Bab Sharq","big_city":"Alexandria" },
    { "id": "107", "governorate_id": "3", "city_name_ar": "برج العرب", "city_name_en": "Bourj Alarab","big_city":"Alexandria" },
    { "id": "108", "governorate_id": "3", "city_name_ar": "ستانلى", "city_name_en": "Stanley","big_city":"Alexandria" },
    { "id": "109", "governorate_id": "3", "city_name_ar": "سموحة", "city_name_en": "Smouha" ,"big_city":"Alexandria"},
    { "id": "110", "governorate_id": "3", "city_name_ar": "سيدى بشر", "city_name_en": "Sidi Bishr" ,"big_city":"Alexandria"},
    { "id": "111", "governorate_id": "3", "city_name_ar": "شدس", "city_name_en": "Shads" ,"big_city":"Alexandria"},
    { "id": "112", "governorate_id": "3", "city_name_ar": "غيط العنب", "city_name_en": "Gheet Alenab","big_city":"Alexandria" },
    { "id": "113", "governorate_id": "3", "city_name_ar": "فلمينج", "city_name_en": "Fleming","big_city":"Alexandria" },
    { "id": "114", "governorate_id": "3", "city_name_ar": "فيكتوريا", "city_name_en": "Victoria","big_city":"Alexandria" },
    { "id": "115", "governorate_id": "3", "city_name_ar": "كامب شيزار", "city_name_en": "Camp Shizar","big_city":"Alexandria" },
    { "id": "116", "governorate_id": "3", "city_name_ar": "كرموز", "city_name_en": "Karmooz","big_city":"Alexandria" },
    { "id": "117", "governorate_id": "3", "city_name_ar": "محطة الرمل", "city_name_en": "Mahta Alraml","big_city":"Alexandria" },
    { "id": "118", "governorate_id": "3", "city_name_ar": "مينا البصل", "city_name_en": "Mina El-Basal" ,"big_city":"Alexandria"},
    { "id": "119", "governorate_id": "3", "city_name_ar": "العصافرة", "city_name_en": "Asafra" ,"big_city":"Alexandria"},
    { "id": "120", "governorate_id": "3", "city_name_ar": "العجمي", "city_name_en": "Agamy" ,"big_city":"Alexandria"},
    { "id": "121", "governorate_id": "3", "city_name_ar": "بكوس", "city_name_en": "Bakos" ,"big_city":"Alexandria"},
    { "id": "122", "governorate_id": "3", "city_name_ar": "بولكلي", "city_name_en": "Boulkly","big_city":"Alexandria" },
    { "id": "123", "governorate_id": "3", "city_name_ar": "كليوباترا", "city_name_en": "Cleopatra","big_city":"Alexandria" },
    { "id": "124", "governorate_id": "3", "city_name_ar": "جليم", "city_name_en": "Glim" ,"big_city":"Alexandria"},
    { "id": "125", "governorate_id": "3", "city_name_ar": "المعمورة", "city_name_en": "Al Mamurah" ,"big_city":"Alexandria"},
    { "id": "126", "governorate_id": "3", "city_name_ar": "المندرة", "city_name_en": "Al Mandara" ,"big_city":"Alexandria"},
    { "id": "127", "governorate_id": "3", "city_name_ar": "محرم بك", "city_name_en": "Moharam Bek","big_city":"Alexandria" },
    { "id": "128", "governorate_id": "3", "city_name_ar": "الشاطبي", "city_name_en": "Elshatby" ,"big_city":"Alexandria"},
    { "id": "129", "governorate_id": "3", "city_name_ar": "سيدي جابر", "city_name_en": "Sidi Gaber" ,"big_city":"Alexandria"},
    { "id": "130", "governorate_id": "3", "city_name_ar": "الساحل الشمالي", "city_name_en": "North Coast sahel" ,"big_city":"Alexandria"},
    { "id": "131", "governorate_id": "3", "city_name_ar": "الحضرة", "city_name_en": "Alhadra" ,"big_city":"Alexandria"},
    { "id": "132", "governorate_id": "3", "city_name_ar": "العطارين", "city_name_en": "Alattarin" ,"big_city":"Alexandria"},
    { "id": "133", "governorate_id": "3", "city_name_ar": "سيدي كرير", "city_name_en": "Sidi Kerir","big_city":"Alexandria" },
    { "id": "134", "governorate_id": "3", "city_name_ar": "الجمرك", "city_name_en": "Elgomrok" ,"big_city":"Alexandria"},
    { "id": "135", "governorate_id": "3", "city_name_ar": "المكس", "city_name_en": "Al Max" ,"big_city":"Alexandria"},
    { "id": "136", "governorate_id": "3", "city_name_ar": "مارينا", "city_name_en": "Marina","big_city":"Alexandria" },

    { "id": "137", "governorate_id": "4", "city_name_ar": "المنصورة", "city_name_en": "Mansoura", "big_city":"Dakahlia"},
    { "id": "138", "governorate_id": "4", "city_name_ar": "طلخا", "city_name_en": "Talkha","big_city":"Dakahlia" },
    { "id": "139", "governorate_id": "4", "city_name_ar": "ميت غمر", "city_name_en": "Mitt Ghamr","big_city":"Dakahlia" },
    { "id": "140", "governorate_id": "4", "city_name_ar": "دكرنس", "city_name_en": "Dekernes" ,"big_city":"Dakahlia"},
    { "id": "141", "governorate_id": "4", "city_name_ar": "أجا", "city_name_en": "Aga" ,"big_city":"Dakahlia"},
    { "id": "142", "governorate_id": "4", "city_name_ar": "منية النصر", "city_name_en": "Menia El Nasr","big_city":"Dakahlia" },
    { "id": "143", "governorate_id": "4", "city_name_ar": "السنبلاوين", "city_name_en": "Sinbillawin" ,"big_city":"Dakahlia"},
    { "id": "144", "governorate_id": "4", "city_name_ar": "الكردي", "city_name_en": "El Kurdi" ,"big_city":"Dakahlia"},
    { "id": "145", "governorate_id": "4", "city_name_ar": "بني عبيد", "city_name_en": "Bani Ubaid","big_city":"Dakahlia" },
    { "id": "146", "governorate_id": "4", "city_name_ar": "المنزلة", "city_name_en": "Al Manzala" ,"big_city":"Dakahlia"},
    { "id": "147", "governorate_id": "4", "city_name_ar": "تمي الأمديد", "city_name_en": "tami al'amdid","big_city":"Dakahlia" },
    { "id": "148", "governorate_id": "4", "city_name_ar": "الجمالية", "city_name_en": "aljamalia" ,"big_city":"Dakahlia"},
    { "id": "149", "governorate_id": "4", "city_name_ar": "شربين", "city_name_en": "Sherbin" ,"big_city":"Dakahlia"},
    { "id": "150", "governorate_id": "4", "city_name_ar": "المطرية", "city_name_en": "Mataria" ,"big_city":"Dakahlia"},
    { "id": "151", "governorate_id": "4", "city_name_ar": "بلقاس", "city_name_en": "Belqas","big_city":"Dakahlia" },
    { "id": "152", "governorate_id": "4", "city_name_ar": "ميت سلسيل", "city_name_en": "Meet Salsil","big_city":"Dakahlia" },
    { "id": "153", "governorate_id": "4", "city_name_ar": "جمصة", "city_name_en": "Gamasa","big_city":"Dakahlia" },
    { "id": "154", "governorate_id": "4", "city_name_ar": "محلة دمنة", "city_name_en": "Mahalat Damana" ,"big_city":"Dakahlia"},
    { "id": "155", "governorate_id": "4", "city_name_ar": "نبروه", "city_name_en": "Nabroh","big_city":"Dakahlia" },

    { "id": "156", "governorate_id": "5", "city_name_ar": "الغردقة", "city_name_en": "Hurghada" ,"big_city":"Red Sea"},
    { "id": "157", "governorate_id": "5", "city_name_ar": "رأس غارب", "city_name_en": "Ras Ghareb" ,"big_city":"Red Sea"},
    { "id": "158", "governorate_id": "5", "city_name_ar": "سفاجا", "city_name_en": "Safaga" ,"big_city":"Red Sea"},
    { "id": "159", "governorate_id": "5", "city_name_ar": "القصير", "city_name_en": "El Qusiar" ,"big_city":"Red Sea"},
    { "id": "160", "governorate_id": "5", "city_name_ar": "مرسى علم", "city_name_en": "Marsa Alam","big_city":"Red Sea" },
    { "id": "161", "governorate_id": "5", "city_name_ar": "الشلاتين", "city_name_en": "Shalatin" ,"big_city":"Red Sea"},
    { "id": "162", "governorate_id": "5", "city_name_ar": "حلايب", "city_name_en": "Halaib" ,"big_city":"Red Sea"},
    { "id": "163", "governorate_id": "5", "city_name_ar": "الدهار", "city_name_en": "Aldahar" ,"big_city":"Red Sea"},

    { "id": "164", "governorate_id": "6", "city_name_ar": "دمنهور", "city_name_en": "Damanhour" ,"big_city":"Beheira"},
    { "id": "165", "governorate_id": "6", "city_name_ar": "كفر الدوار", "city_name_en": "Kafr El Dawar","big_city":"Beheira" },
    { "id": "166", "governorate_id": "6", "city_name_ar": "رشيد", "city_name_en": "Rashid" ,"big_city":"Beheira"},
    { "id": "167", "governorate_id": "6", "city_name_ar": "إدكو", "city_name_en": "Edco" ,"big_city":"Beheira"},
    { "id": "168", "governorate_id": "6", "city_name_ar": "أبو المطامير", "city_name_en": "Abu al-Matamir" ,"big_city":"Beheira"},
    { "id": "169", "governorate_id": "6", "city_name_ar": "أبو حمص", "city_name_en": "Abu Homs","big_city":"Beheira" },
    { "id": "170", "governorate_id": "6", "city_name_ar": "الدلنجات", "city_name_en": "Delengat","big_city":"Beheira" },
    { "id": "171", "governorate_id": "6", "city_name_ar": "المحمودية", "city_name_en": "Mahmoudiyah","big_city":"Beheira" },
    { "id": "172", "governorate_id": "6", "city_name_ar": "الرحمانية", "city_name_en": "Rahmaniyah" ,"big_city":"Beheira"},
    { "id": "173", "governorate_id": "6", "city_name_ar": "إيتاي البارود", "city_name_en": "Itai Baroud","big_city":"Beheira" },
    { "id": "174", "governorate_id": "6", "city_name_ar": "حوش عيسى", "city_name_en": "Housh Eissa","big_city":"Beheira" },
    { "id": "175", "governorate_id": "6", "city_name_ar": "شبراخيت", "city_name_en": "Shubrakhit","big_city":"Beheira" },
    { "id": "176", "governorate_id": "6", "city_name_ar": "كوم حمادة", "city_name_en": "Kom Hamada","big_city":"Beheira" },
    { "id": "177", "governorate_id": "6", "city_name_ar": "بدر", "city_name_en": "Badr","big_city":"Beheira" },
    { "id": "178", "governorate_id": "6", "city_name_ar": "وادي النطرون", "city_name_en": "Wadi Natrun","big_city":"Beheira" },
    { "id": "179", "governorate_id": "6", "city_name_ar": "النوبارية الجديدة", "city_name_en": "New Nubaria" ,"big_city":"Beheira"},
    { "id": "180", "governorate_id": "6", "city_name_ar": "النوبارية", "city_name_en": "Alnoubareya" ,"big_city":"Beheira"},

    { "id": "181", "governorate_id": "7", "city_name_ar": "الفيوم", "city_name_en": "Fayoum" ,"big_city":"Fayoum"},
    { "id": "182", "governorate_id": "7", "city_name_ar": "الفيوم الجديدة", "city_name_en": "Fayoum El Gedida" ,"big_city":"Fayoum"},
    { "id": "183", "governorate_id": "7", "city_name_ar": "طامية", "city_name_en": "Tamiya" ,"big_city":"Fayoum"},
    { "id": "184", "governorate_id": "7", "city_name_ar": "سنورس", "city_name_en": "Snores" ,"big_city":"Fayoum"},
    { "id": "185", "governorate_id": "7", "city_name_ar": "إطسا", "city_name_en": "Etsa" ,"big_city":"Fayoum"},
    { "id": "186", "governorate_id": "7", "city_name_ar": "إبشواي", "city_name_en": "Epschway" ,"big_city":"Fayoum"},
    { "id": "187", "governorate_id": "7", "city_name_ar": "يوسف الصديق", "city_name_en": "Yusuf El Sediaq","big_city":"Fayoum" },
    { "id": "188", "governorate_id": "7", "city_name_ar": "الحادقة", "city_name_en": "Hadqa" ,"big_city":"Fayoum"},
    { "id": "189", "governorate_id": "7", "city_name_ar": "اطسا", "city_name_en": "Atsa" ,"big_city":"Fayoum"},
    { "id": "190", "governorate_id": "7", "city_name_ar": "الجامعة", "city_name_en": "Algamaa","big_city":"Fayoum" },
    { "id": "191", "governorate_id": "7", "city_name_ar": "السيالة", "city_name_en": "Sayala" ,"big_city":"Fayoum"},

    { "id": "192", "governorate_id": "8", "city_name_ar": "طنطا", "city_name_en": "Tanta", "big_city":"Gharbiya" },
    { "id": "193", "governorate_id": "8", "city_name_ar": "المحلة الكبرى", "city_name_en": "Al Mahalla Al Kobra", "big_city":"Gharbiya" },
    { "id": "194", "governorate_id": "8", "city_name_ar": "كفر الزيات", "city_name_en": "Kafr El Zayat", "big_city":"Gharbiya" },
    { "id": "195", "governorate_id": "8", "city_name_ar": "زفتى", "city_name_en": "Zefta", "big_city":"Gharbiya" },
    { "id": "196", "governorate_id": "8", "city_name_ar": "السنطة", "city_name_en": "El Santa", "big_city":"Gharbiya" },
    { "id": "197", "governorate_id": "8", "city_name_ar": "قطور", "city_name_en": "Qutour" , "big_city":"Gharbiya"},
    { "id": "198", "governorate_id": "8", "city_name_ar": "بسيون", "city_name_en": "Basion" , "big_city":"Gharbiya"},
    { "id": "199", "governorate_id": "8", "city_name_ar": "سمنود", "city_name_en": "Samannoud", "big_city":"Gharbiya" },
    
    { "id": "200", "governorate_id": "9", "city_name_ar": "الإسماعيلية", "city_name_en": "Ismailia" , "big_city":"Ismailia"},
    { "id": "201", "governorate_id": "9", "city_name_ar": "فايد", "city_name_en": "Fayed" ,"big_city":"Ismailia"},
    { "id": "202", "governorate_id": "9", "city_name_ar": "القنطرة شرق", "city_name_en": "Qantara Sharq" ,"big_city":"Ismailia"},
    { "id": "203", "governorate_id": "9", "city_name_ar": "القنطرة غرب", "city_name_en": "Qantara Gharb" ,"big_city":"Ismailia"},
    { "id": "204", "governorate_id": "9", "city_name_ar": "التل الكبير", "city_name_en": "El Tal El Kabier","big_city":"Ismailia" },
    { "id": "205", "governorate_id": "9", "city_name_ar": "أبو صوير", "city_name_en": "Abu Sawir" ,"big_city":"Ismailia"},
    { "id": "206", "governorate_id": "9", "city_name_ar": "القصاصين الجديدة", "city_name_en": "Kasasien El Gedida" ,"big_city":"Ismailia"},
    { "id": "207", "governorate_id": "9", "city_name_ar": "نفيشة", "city_name_en": "Nefesha" ,"big_city":"Ismailia"},
    { "id": "208", "governorate_id": "9", "city_name_ar": "الشيخ زايد", "city_name_en": "Sheikh Zayed" ,"big_city":"Ismailia"},

    { "id": "209", "governorate_id": "10", "city_name_ar": "شبين الكوم", "city_name_en": "Shbeen El Koom", "big_city":"Menofia" },
    { "id": "210", "governorate_id": "10", "city_name_ar": "مدينة السادات", "city_name_en": "Sadat City" , "big_city":"Menofia"},
    { "id": "211", "governorate_id": "10", "city_name_ar": "منوف", "city_name_en": "Menouf" , "big_city":"Menofia"},
    { "id": "212", "governorate_id": "10", "city_name_ar": "سرس الليان", "city_name_en": "Sars El-Layan", "big_city":"Menofia" },
    { "id": "213", "governorate_id": "10", "city_name_ar": "أشمون", "city_name_en": "Ashmon" , "big_city":"Menofia"},
    { "id": "214", "governorate_id": "10", "city_name_ar": "الباجور", "city_name_en": "Al Bagor" , "big_city":"Menofia"},
    { "id": "215", "governorate_id": "10", "city_name_ar": "قويسنا", "city_name_en": "Quesna", "big_city":"Menofia" },
    { "id": "216", "governorate_id": "10", "city_name_ar": "بركة السبع", "city_name_en": "Berkat El Saba", "big_city":"Menofia" },
    { "id": "217", "governorate_id": "10", "city_name_ar": "تلا", "city_name_en": "Tala" , "big_city":"Menofia"},
    { "id": "218", "governorate_id": "10", "city_name_ar": "الشهداء", "city_name_en": "Al Shohada", "big_city":"Menofia" },

    { "id": "219", "governorate_id": "11", "city_name_ar": "المنيا", "city_name_en": "Minya" , "big_city":"Minya" },
    { "id": "220", "governorate_id": "11", "city_name_ar": "المنيا الجديدة", "city_name_en": "Minya El Gedida" , "big_city":"Minya"},
    { "id": "221", "governorate_id": "11", "city_name_ar": "العدوة", "city_name_en": "El Adwa" , "big_city":"Minya"},
    { "id": "222", "governorate_id": "11", "city_name_ar": "مغاغة", "city_name_en": "Magagha" , "big_city":"Minya"},
    { "id": "223", "governorate_id": "11", "city_name_ar": "بني مزار", "city_name_en": "Bani Mazar", "big_city":"Minya" },
    { "id": "224", "governorate_id": "11", "city_name_ar": "مطاي", "city_name_en": "Mattay" , "big_city":"Minya"},
    { "id": "225", "governorate_id": "11", "city_name_ar": "سمالوط", "city_name_en": "Samalut" , "big_city":"Minya"},
    { "id": "226", "governorate_id": "11", "city_name_ar": "المدينة الفكرية", "city_name_en": "Madinat El Fekria", "big_city":"Minya" },
    { "id": "227", "governorate_id": "11", "city_name_ar": "ملوي", "city_name_en": "Meloy", "big_city":"Minya" },
    { "id": "228", "governorate_id": "11", "city_name_ar": "دير مواس", "city_name_en": "Deir Mawas" , "big_city":"Minya"},
    { "id": "229", "governorate_id": "11", "city_name_ar": "ابو قرقاص", "city_name_en": "Abu Qurqas", "big_city":"Minya" },
    { "id": "230", "governorate_id": "11", "city_name_ar": "ارض سلطان", "city_name_en": "Ard Sultan" , "big_city":"Minya"},

    { "id": "231", "governorate_id": "12", "city_name_ar": "بنها", "city_name_en": "Banha" , "big_city":"Qaliubiya"},
    { "id": "232", "governorate_id": "12", "city_name_ar": "قليوب", "city_name_en": "Qalyub" , "big_city":"Qaliubiya"},
    { "id": "233", "governorate_id": "12", "city_name_ar": "شبرا الخيمة", "city_name_en": "Shubra Al Khaimah" , "big_city":"Qaliubiya"},
    { "id": "234", "governorate_id": "12", "city_name_ar": "القناطر الخيرية", "city_name_en": "Al Qanater Charity" , "big_city":"Qaliubiya"},
    { "id": "235", "governorate_id": "12", "city_name_ar": "الخانكة", "city_name_en": "Khanka" , "big_city":"Qaliubiya"},
    { "id": "236", "governorate_id": "12", "city_name_ar": "كفر شكر", "city_name_en": "Kafr Shukr" , "big_city":"Qaliubiya"},
    { "id": "237", "governorate_id": "12", "city_name_ar": "طوخ", "city_name_en": "Tukh" , "big_city":"Qaliubiya"},
    { "id": "238", "governorate_id": "12", "city_name_ar": "قها", "city_name_en": "Qaha" , "big_city":"Qaliubiya"},
    { "id": "239", "governorate_id": "12", "city_name_ar": "العبور", "city_name_en": "Obour", "big_city":"Qaliubiya" },
    { "id": "240", "governorate_id": "12", "city_name_ar": "الخصوص", "city_name_en": "Khosous" , "big_city":"Qaliubiya"},
    { "id": "241", "governorate_id": "12", "city_name_ar": "شبين القناطر", "city_name_en": "Shibin Al Qanater", "big_city":"Qaliubiya" },
    { "id": "242", "governorate_id": "12", "city_name_ar": "مسطرد", "city_name_en": "Mostorod" , "big_city":"Qaliubiya"},
    
    { "id": "243", "governorate_id": "13", "city_name_ar": "الخارجة", "city_name_en": "El Kharga"  , "big_city":"New Valley"},
    { "id": "244", "governorate_id": "13", "city_name_ar": "باريس", "city_name_en": "Paris"  , "big_city":"New Valley"},
    { "id": "245", "governorate_id": "13", "city_name_ar": "موط", "city_name_en": "Mout"  , "big_city":"New Valley"},
    { "id": "246", "governorate_id": "13", "city_name_ar": "الفرافرة", "city_name_en": "Farafra" , "big_city":"New Valley" },
    { "id": "247", "governorate_id": "13", "city_name_ar": "بلاط", "city_name_en": "Balat" , "big_city":"New Valley" },
    { "id": "248", "governorate_id": "13", "city_name_ar": "الداخلة", "city_name_en": "Dakhla" , "big_city":"New Valley" },

    { "id": "249", "governorate_id": "14", "city_name_ar": "السويس", "city_name_en": "Suez"  , "big_city":"Suez"},
    { "id": "250", "governorate_id": "14", "city_name_ar": "الجناين", "city_name_en": "Alganayen"  , "big_city":"Suez"},
    { "id": "251", "governorate_id": "14", "city_name_ar": "عتاقة", "city_name_en": "Ataqah" , "big_city":"Suez" },
    { "id": "252", "governorate_id": "14", "city_name_ar": "العين السخنة", "city_name_en": "Ain Sokhna" , "big_city":"Suez" },
    { "id": "253", "governorate_id": "14", "city_name_ar": "فيصل", "city_name_en": "Faysal"  , "big_city":"Suez"},

    { "id": "254", "governorate_id": "15", "city_name_ar": "أسوان", "city_name_en": "Aswan" ,"big_city":"Aswan"},
    { "id": "255", "governorate_id": "15", "city_name_ar": "أسوان الجديدة", "city_name_en": "Aswan El Gedida","big_city":"Aswan" },
    { "id": "256", "governorate_id": "15", "city_name_ar": "دراو", "city_name_en": "Drau" ,"big_city":"Aswan"},
    { "id": "257", "governorate_id": "15", "city_name_ar": "كوم أمبو", "city_name_en": "Kom Ombo" ,"big_city":"Aswan"},
    { "id": "258", "governorate_id": "15", "city_name_ar": "نصر النوبة", "city_name_en": "Nasr Al Nuba" ,"big_city":"Aswan"},
    { "id": "259", "governorate_id": "15", "city_name_ar": "كلابشة", "city_name_en": "Kalabsha" ,"big_city":"Aswan"},
    { "id": "260", "governorate_id": "15", "city_name_ar": "إدفو", "city_name_en": "Edfu" ,"big_city":"Aswan"},
    { "id": "261", "governorate_id": "15", "city_name_ar": "الرديسية", "city_name_en": "Al-Radisiyah" ,"big_city":"Aswan"},
    { "id": "262", "governorate_id": "15", "city_name_ar": "البصيلية", "city_name_en": "Al Basilia" ,"big_city":"Aswan"},
    { "id": "263", "governorate_id": "15", "city_name_ar": "السباعية", "city_name_en": "Al Sibaeia" ,"big_city":"Aswan"},
    { "id": "264", "governorate_id": "15", "city_name_ar": "ابوسمبل السياحية", "city_name_en": "Abo Simbl Al Siyahia","big_city":"Aswan" },
    { "id": "265", "governorate_id": "15", "city_name_ar": "مرسى علم", "city_name_en": "Marsa Alam","big_city":"Aswan" },

    
    { "id": "266", "governorate_id": "16", "city_name_ar": "أسيوط", "city_name_en": "Assiut","big_city":"Assiut" },
    { "id": "267", "governorate_id": "16", "city_name_ar": "أسيوط الجديدة", "city_name_en": "Assiut El Gedida","big_city":"Assiut" },
    { "id": "268", "governorate_id": "16", "city_name_ar": "ديروط", "city_name_en": "Dayrout" ,"big_city":"Assiut"},
    { "id": "269", "governorate_id": "16", "city_name_ar": "منفلوط", "city_name_en": "Manfalut" ,"big_city":"Assiut"},
    { "id": "270", "governorate_id": "16", "city_name_ar": "القوصية", "city_name_en": "Qusiya" ,"big_city":"Assiut"},
    { "id": "271", "governorate_id": "16", "city_name_ar": "أبنوب", "city_name_en": "Abnoub","big_city":"Assiut" },
    { "id": "272", "governorate_id": "16", "city_name_ar": "أبو تيج", "city_name_en": "Abu Tig" ,"big_city":"Assiut"},
    { "id": "273", "governorate_id": "16", "city_name_ar": "الغنايم", "city_name_en": "El Ghanaim" ,"big_city":"Assiut"},
    { "id": "274", "governorate_id": "16", "city_name_ar": "ساحل سليم", "city_name_en": "Sahel Selim","big_city":"Assiut" },
    { "id": "275", "governorate_id": "16", "city_name_ar": "البداري", "city_name_en": "El Badari","big_city":"Assiut" },
    { "id": "276", "governorate_id": "16", "city_name_ar": "صدفا", "city_name_en": "Sidfa" ,"big_city":"Assiut"},

    { "id": "277", "governorate_id": "17", "city_name_ar": "بني سويف", "city_name_en": "Bani Sweif","big_city":"Beni Suef" },
    { "id": "278", "governorate_id": "17", "city_name_ar": "بني سويف الجديدة", "city_name_en": "Beni Suef El Gedida","big_city":"Beni Suef" },
    { "id": "279", "governorate_id": "17", "city_name_ar": "الواسطى", "city_name_en": "Al Wasta","big_city":"Beni Suef" },
    { "id": "280", "governorate_id": "17", "city_name_ar": "ناصر", "city_name_en": "Naser" ,"big_city":"Beni Suef"},
    { "id": "281", "governorate_id": "17", "city_name_ar": "إهناسيا", "city_name_en": "Ehnasia" ,"big_city":"Beni Suef"},
    { "id": "282", "governorate_id": "17", "city_name_ar": "ببا", "city_name_en": "beba" ,"big_city":"Beni Suef"},
    { "id": "283", "governorate_id": "17", "city_name_ar": "الفشن", "city_name_en": "Fashn" ,"big_city":"Beni Suef"},
    { "id": "284", "governorate_id": "17", "city_name_ar": "سمسطا", "city_name_en": "Somasta" ,"big_city":"Beni Suef"},
    { "id": "285", "governorate_id": "17", "city_name_ar": "الاباصيرى", "city_name_en": "Alabbaseri","big_city":"Beni Suef" },
    { "id": "286", "governorate_id": "17", "city_name_ar": "مقبل", "city_name_en": "Mokbel","big_city":"Beni Suef" },

    { "id": "287", "governorate_id": "18", "city_name_ar": "بورسعيد", "city_name_en": "PorSaid" ,"big_city":"Port Said"},
    { "id": "288", "governorate_id": "18", "city_name_ar": "بورفؤاد", "city_name_en": "Port Fouad" ,"big_city":"Port Said"},
    { "id": "289", "governorate_id": "18", "city_name_ar": "العرب", "city_name_en": "Alarab" ,"big_city":"Port Said"},
    { "id": "290", "governorate_id": "18", "city_name_ar": "حى الزهور", "city_name_en": "Zohour" ,"big_city":"Port Said"},
    { "id": "291", "governorate_id": "18", "city_name_ar": "حى الشرق", "city_name_en": "Alsharq" ,"big_city":"Port Said"},
    { "id": "292", "governorate_id": "18", "city_name_ar": "حى الضواحى", "city_name_en": "Aldawahi" ,"big_city":"Port Said"},
    { "id": "293", "governorate_id": "18", "city_name_ar": "حى المناخ", "city_name_en": "Almanakh" ,"big_city":"Port Said"},
    { "id": "294", "governorate_id": "18", "city_name_ar": "حى مبارك", "city_name_en": "Mubarak" ,"big_city":"Port Said"},
    
    { "id": "295", "governorate_id": "19", "city_name_ar": "دمياط", "city_name_en": "Damietta" ,"big_city":"Damietta"},
    { "id": "296", "governorate_id": "19", "city_name_ar": "دمياط الجديدة", "city_name_en": "New Damietta" ,"big_city":"Damietta"},
    { "id": "297", "governorate_id": "19", "city_name_ar": "رأس البر", "city_name_en": "Ras El Bar" ,"big_city":"Damietta"},
    { "id": "298", "governorate_id": "19", "city_name_ar": "فارسكور", "city_name_en": "Faraskour" ,"big_city":"Damietta"},
    { "id": "299", "governorate_id": "19", "city_name_ar": "الزرقا", "city_name_en": "Zarqa","big_city":"Damietta" },
    { "id": "300", "governorate_id": "19", "city_name_ar": "السرو", "city_name_en": "alsaru" ,"big_city":"Damietta"},
    { "id": "301", "governorate_id": "19", "city_name_ar": "الروضة", "city_name_en": "alruwda" ,"big_city":"Damietta"},
    { "id": "302", "governorate_id": "19", "city_name_ar": "كفر البطيخ", "city_name_en": "Kafr El-Batikh","big_city":"Damietta" },
    { "id": "303", "governorate_id": "19", "city_name_ar": "عزبة البرج", "city_name_en": "Azbet Al Burg" ,"big_city":"Damietta"},
    { "id": "304", "governorate_id": "19", "city_name_ar": "ميت أبو غالب", "city_name_en": "Meet Abou Ghalib" ,"big_city":"Damietta"},
    { "id": "305", "governorate_id": "19", "city_name_ar": "كفر سعد", "city_name_en": "Kafr Saad" ,"big_city":"Damietta"},

    { "id": "306", "governorate_id": "20", "city_name_ar": "الزقازيق", "city_name_en": "Zagazig","big_city":"Sharkia" },
    { "id": "307", "governorate_id": "20", "city_name_ar": "العاشر من رمضان", "city_name_en": "Al Ashr Men Ramadan","big_city":"Sharkia" },
    { "id": "308", "governorate_id": "20", "city_name_ar": "منيا القمح", "city_name_en": "Minya Al Qamh","big_city":"Sharkia"},
    { "id": "309", "governorate_id": "20", "city_name_ar": "بلبيس", "city_name_en": "Belbeis","big_city":"Sharkia" },
    { "id": "310", "governorate_id": "20", "city_name_ar": "مشتول السوق", "city_name_en": "Mashtoul El Souq" ,"big_city":"Sharkia"},
    { "id": "311", "governorate_id": "20", "city_name_ar": "القنايات", "city_name_en": "Qenaiat","big_city":"Sharkia" },
    { "id": "312", "governorate_id": "20", "city_name_ar": "أبو حماد", "city_name_en": "Abu Hammad","big_city":"Sharkia" },
    { "id": "313", "governorate_id": "20", "city_name_ar": "القرين", "city_name_en": "El Qurain","big_city":"Sharkia" },
    { "id": "314", "governorate_id": "20", "city_name_ar": "ههيا", "city_name_en": "Hehia" ,"big_city":"Sharkia"},
    { "id": "315", "governorate_id": "20", "city_name_ar": "أبو كبير", "city_name_en": "Abu Kabir" ,"big_city":"Sharkia"},
    { "id": "316", "governorate_id": "20", "city_name_ar": "فاقوس", "city_name_en": "Faccus","big_city":"Sharkia"},
    { "id": "317", "governorate_id": "20", "city_name_ar": "الصالحية الجديدة", "city_name_en": "El Salihia El Gedida" ,"big_city":"Sharkia"},
    { "id": "318", "governorate_id": "20", "city_name_ar": "الإبراهيمية", "city_name_en": "Al Ibrahimiyah","big_city":"Sharkia" },
    { "id": "319", "governorate_id": "20", "city_name_ar": "ديرب نجم", "city_name_en": "Deirb Negm" ,"big_city":"Sharkia"},
    { "id": "320", "governorate_id": "20", "city_name_ar": "كفر صقر", "city_name_en": "Kafr Saqr" ,"big_city":"Sharkia"},
    { "id": "321", "governorate_id": "20", "city_name_ar": "أولاد صقر", "city_name_en": "Awlad Saqr" ,"big_city":"Sharkia"},
    { "id": "322", "governorate_id": "20", "city_name_ar": "الحسينية", "city_name_en": "Husseiniya" ,"big_city":"Sharkia"},
    { "id": "323", "governorate_id": "20", "city_name_ar": "صان الحجر القبلية", "city_name_en": "san alhajar alqablia" ,"big_city":"Sharkia"},
    { "id": "324", "governorate_id": "20", "city_name_ar": "منشأة أبو عمر", "city_name_en": "Manshayat Abu Omar","big_city":"Sharkia" },

    
    { "id": "325", "governorate_id": "21", "city_name_ar": "الطور", "city_name_en": "Al Toor","big_city":"South Sinai" },
    { "id": "326", "governorate_id": "21", "city_name_ar": "شرم الشيخ", "city_name_en": "Sharm El-Shaikh","big_city":"South Sinai" },
    { "id": "327", "governorate_id": "21", "city_name_ar": "دهب", "city_name_en": "Dahab" ,"big_city":"South Sinai"},
    { "id": "328", "governorate_id": "21", "city_name_ar": "نويبع", "city_name_en": "Nuweiba","big_city":"South Sinai" },
    { "id": "329", "governorate_id": "21", "city_name_ar": "طابا", "city_name_en": "Taba" ,"big_city":"South Sinai"},
    { "id": "330", "governorate_id": "21", "city_name_ar": "سانت كاترين", "city_name_en": "Saint Catherine" ,"big_city":"South Sinai"},
    { "id": "331", "governorate_id": "21", "city_name_ar": "أبو رديس", "city_name_en": "Abu Redis" ,"big_city":"South Sinai"},
    { "id": "332", "governorate_id": "21", "city_name_ar": "أبو زنيمة", "city_name_en": "Abu Zenaima" ,"big_city":"South Sinai"},
    { "id": "333", "governorate_id": "21", "city_name_ar": "رأس سدر", "city_name_en": "Ras Sidr","big_city":"South Sinai"},


    { "id": "334", "governorate_id": "22", "city_name_ar": "كفر الشيخ", "city_name_en": "Kafr El Sheikh","big_city":"Kafr Al Sheikh" },
    { "id": "335", "governorate_id": "22", "city_name_ar": "وسط البلد كفر الشيخ", "city_name_en": "Kafr El Sheikh Downtown" ,"big_city":"Kafr Al Sheikh"},
    { "id": "336", "governorate_id": "22", "city_name_ar": "دسوق", "city_name_en": "Desouq" ,"big_city":"Kafr Al Sheikh"},
    { "id": "337", "governorate_id": "22", "city_name_ar": "فوه", "city_name_en": "Fooh" ,"big_city":"Kafr Al Sheikh"},
    { "id": "338", "governorate_id": "22", "city_name_ar": "مطوبس", "city_name_en": "Metobas" ,"big_city":"Kafr Al Sheikh"},
    { "id": "339", "governorate_id": "22", "city_name_ar": "برج البرلس", "city_name_en": "Burg Al Burullus","big_city":"Kafr Al heikh" },
    { "id": "340", "governorate_id": "22", "city_name_ar": "بلطيم", "city_name_en": "Baltim" ,"big_city":"Kafr Al Sheikh"},
    { "id": "341", "governorate_id": "22", "city_name_ar": "مصيف بلطيم", "city_name_en": "Masief Baltim" ,"big_city":"Kafr Al Sheikh"},
    { "id": "342", "governorate_id": "22", "city_name_ar": "الحامول", "city_name_en": "Hamol" ,"big_city":"Kafr Al Sheikh"},
    { "id": "343", "governorate_id": "22", "city_name_ar": "بيلا", "city_name_en": "Bella" ,"big_city":"Kafr Al Sheikh"},
    { "id": "344", "governorate_id": "22", "city_name_ar": "الرياض", "city_name_en": "Riyadh" ,"big_city":"Kafr Al Sheikh"},
    { "id": "345", "governorate_id": "22", "city_name_ar": "سيدي سالم", "city_name_en": "Sidi Salm" ,"big_city":"Kafr Al Sheikh"},
    { "id": "346", "governorate_id": "22", "city_name_ar": "قلين", "city_name_en": "Qellen" ,"big_city":"Kafr Al Sheikh"},
    { "id": "347", "governorate_id": "22", "city_name_ar": "سيدي غازي", "city_name_en": "Sidi Ghazi" ,"big_city":"Kafr Al Sheikh"},
    
    { "id": "348", "governorate_id": "23", "city_name_ar": "مرسى مطروح", "city_name_en": "Marsa Matrouh" ,"big_city":"Matrouh"},
    { "id": "349", "governorate_id": "23", "city_name_ar": "الحمام", "city_name_en": "El Hamam" ,"big_city":"Matrouh"},
    { "id": "350", "governorate_id": "23", "city_name_ar": "العلمين", "city_name_en": "Alamein" ,"big_city":"Matrouh"},
    { "id": "351", "governorate_id": "23", "city_name_ar": "الضبعة", "city_name_en": "Dabaa" ,"big_city":"Matrouh"},
    { "id": "352", "governorate_id": "23", "city_name_ar": "النجيلة", "city_name_en": "Al-Nagila" ,"big_city":"Matrouh"},
    { "id": "353", "governorate_id": "23", "city_name_ar": "سيدي براني", "city_name_en": "Sidi Brani" ,"big_city":"Matrouh"},
    { "id": "354", "governorate_id": "23", "city_name_ar": "السلوم", "city_name_en": "Salloum" ,"big_city":"Matrouh"},
    { "id": "355", "governorate_id": "23", "city_name_ar": "سيوة", "city_name_en": "Siwa" ,"big_city":"Matrouh"},
    { "id": "356", "governorate_id": "23", "city_name_ar": "مارينا", "city_name_en": "Marina" ,"big_city":"Matrouh"},
    { "id": "357", "governorate_id": "23", "city_name_ar": "الساحل الشمالى", "city_name_en": "North Coast" ,"big_city":"Matrouh"},

    { "id": "358", "governorate_id": "24", "city_name_ar": "الأقصر", "city_name_en": "Luxor" ,"big_city":"Luxor"},
    { "id": "359", "governorate_id": "24", "city_name_ar": "الأقصر الجديدة", "city_name_en": "New Luxor" ,"big_city":"Luxor"},
    { "id": "360", "governorate_id": "24", "city_name_ar": "إسنا", "city_name_en": "Esna" ,"big_city":"Luxor"},
    { "id": "361", "governorate_id": "24", "city_name_ar": "طيبة الجديدة", "city_name_en": "New Tiba" ,"big_city":"Luxor"},
    { "id": "362", "governorate_id": "24", "city_name_ar": "الزينية", "city_name_en": "Al ziynia" ,"big_city":"Luxor"},
    { "id": "363", "governorate_id": "24", "city_name_ar": "البياضية", "city_name_en": "Al Bayadieh" ,"big_city":"Luxor"},
    { "id": "364", "governorate_id": "24", "city_name_ar": "القرنة", "city_name_en": "Al Qarna" ,"big_city":"Luxor"},
    { "id": "365", "governorate_id": "24", "city_name_ar": "أرمنت", "city_name_en": "Armant" ,"big_city":"Luxor"},
    { "id": "366", "governorate_id": "24", "city_name_ar": "الطود", "city_name_en": "Al Tud" ,"big_city":"Luxor"},

    { "id": "367", "governorate_id": "25", "city_name_ar": "قنا", "city_name_en": "Qena" ,"big_city":"Qena"},
    { "id": "368", "governorate_id": "25", "city_name_ar": "قنا الجديدة", "city_name_en": "New Qena","big_city":"Qena" },
    { "id": "369", "governorate_id": "25", "city_name_ar": "ابو طشت", "city_name_en": "Abu Tesht" ,"big_city":"Qena"},
    { "id": "370", "governorate_id": "25", "city_name_ar": "نجع حمادي", "city_name_en": "Nag Hammadi" ,"big_city":"Qena"},
    { "id": "371", "governorate_id": "25", "city_name_ar": "دشنا", "city_name_en": "Deshna" ,"big_city":"Qena"},
    { "id": "372", "governorate_id": "25", "city_name_ar": "الوقف", "city_name_en": "Alwaqf" ,"big_city":"Qena"},
    { "id": "373", "governorate_id": "25", "city_name_ar": "قفط", "city_name_en": "Qaft" ,"big_city":"Qena"},
    { "id": "374", "governorate_id": "25", "city_name_ar": "نقادة", "city_name_en": "Naqada" ,"big_city":"Qena"},
    { "id": "375", "governorate_id": "25", "city_name_ar": "فرشوط", "city_name_en": "Farshout" ,"big_city":"Qena"},
    { "id": "376", "governorate_id": "25", "city_name_ar": "قوص", "city_name_en": "Quos" ,"big_city":"Qena"},
    
    { "id": "377", "governorate_id": "26", "city_name_ar": "العريش", "city_name_en": "Arish"  ,"big_city":"North Sinai"},
    { "id": "378", "governorate_id": "26", "city_name_ar": "الشيخ زويد", "city_name_en": "Sheikh Zowaid"  ,"big_city":"North Sinai"},
    { "id": "379", "governorate_id": "26", "city_name_ar": "نخل", "city_name_en": "Nakhl"  ,"big_city":"North Sinai"},
    { "id": "380", "governorate_id": "26", "city_name_ar": "رفح", "city_name_en": "Rafah"  ,"big_city":"North Sinai"},
    { "id": "381", "governorate_id": "26", "city_name_ar": "بئر العبد", "city_name_en": "Bir al-Abed" ,"big_city":"North Sinai" },
    { "id": "382", "governorate_id": "26", "city_name_ar": "الحسنة", "city_name_en": "Al Hasana"  ,"big_city":"North Sinai"},

    { "id": "383", "governorate_id": "27", "city_name_ar": "سوهاج", "city_name_en": "Sohag" ,"big_city":"Sohag"},
    { "id": "384", "governorate_id": "27", "city_name_ar": "سوهاج الجديدة", "city_name_en": "Sohag El Gedida" ,"big_city":"Sohag"},
    { "id": "385", "governorate_id": "27", "city_name_ar": "أخميم", "city_name_en": "Akhmeem" ,"big_city":"Sohag"},
    { "id": "386", "governorate_id": "27", "city_name_ar": "أخميم الجديدة", "city_name_en": "Akhmim El Gedida" ,"big_city":"Sohag"},
    { "id": "387", "governorate_id": "27", "city_name_ar": "البلينا", "city_name_en": "Albalina" ,"big_city":"Sohag"},
    { "id": "388", "governorate_id": "27", "city_name_ar": "المراغة", "city_name_en": "El Maragha" ,"big_city":"Sohag"},
    { "id": "389", "governorate_id": "27", "city_name_ar": "المنشأة", "city_name_en": "almunsha'a" ,"big_city":"Sohag"},
    { "id": "390", "governorate_id": "27", "city_name_ar": "دار السلام", "city_name_en": "Dar AISalaam" ,"big_city":"Sohag"},
    { "id": "391", "governorate_id": "27", "city_name_ar": "جرجا", "city_name_en": "Gerga" ,"big_city":"Sohag"},
    { "id": "392", "governorate_id": "27", "city_name_ar": "جهينة الغربية", "city_name_en": "Jahina Al Gharbia" ,"big_city":"Sohag"},
    { "id": "393", "governorate_id": "27", "city_name_ar": "ساقلته", "city_name_en": "Saqilatuh" ,"big_city":"Sohag"},
    { "id": "394", "governorate_id": "27", "city_name_ar": "طما", "city_name_en": "Tama" ,"big_city":"Sohag"},
    { "id": "395", "governorate_id": "27", "city_name_ar": "طهطا", "city_name_en": "Tahta" ,"big_city":"Sohag"},
    { "id": "396", "governorate_id": "27", "city_name_ar": "الكوثر", "city_name_en": "Alkawthar" ,"big_city":"Sohag"}
]