export const states=[
      "Alexandria",
      "Aswan",
      "Assiut",
      "Beheira",
      "Beni Suef",
      "Cairo",
      "Dakahlia",
      "Damietta",
      "Fayoum",
      "Gharbiya",
      "Giza",
      "Ismailia",
      "Kafr Al Sheikh",
      "Luxor",
      "Matrouh",
      "Menofia",
      "Minya",
      "New Valley",
      "North Sinai",
      "Port Said",
      "Qaliubiya",
      "Qena",
      "Red Sea",
      "Sharkia",
      "Sohag",
      "South Sinai",
      "Suez"
]